import { create } from "zustand";

const savedLang = localStorage.getItem("lang") || "en";

const translations = {
  en: {
    dashboard: "Dashboard",
    newSale: "New Sale",
    purchase: "Purchase",
    notifications: "Notifications",
    live: "Live",
    viewStockAlerts: "View stock alerts",
    totalSales: "Total Sales",
    purchases: "Purchases",
    dueAmount: "Due Amount",
    lowStockItems: "Low Stock Items",
    sales: "sales",
    cost: "Cost",
    pending: "Pending",
    alert: "Alert",
    myProfile: "My Profile",
    reports: "Reports",
    settings: "Settings",
    signOut: "Sign Out",
    noStore: "No Store",
    noRole: "No Role",
    language: "Language",
    english: "English",
    bangla: "বাংলা",
    // side bar
    saleHistory: "Sale History",
    saleReturns: "Sale Returns",
    installments: "Installments",
    newPurchase: "New Purchase",
    purchaseHistory: "Purchase History",
    purchaseReturns: "Purchase Returns",
    inventory: "Inventory",
    stockOverview: "Stock Overview",
    lowStockAlert: "Low Stock Alert",
    stockTransfer: "Stock Transfer",
    damageStock: "Damage Stock",
    products: "Products",
    allProducts: "All Products",
    addProduct: "Add Product",
    categories: "Categories",
    customers: "Customers",
    allCustomers: "All Customers",
    addCustomer: "Add Customer",
    suppliers: "Suppliers",
    allSuppliers: "All Suppliers",
    addSupplier: "Add Supplier",
    expenses: "Expenses",
    allExpenses: "All Expenses",
    addExpense: "Add Expense",
    yearlyTracking: "Yearly Tracking",
    salesReport: "Sales Report",
    purchaseReport: "Purchase Report",
    inventoryReport: "Inventory Report",
    expenseReport: "Expense Report",
    profitLoss: "Profit & Loss",
    reportsOverview: "Reports Overview",
    dailySales: "Daily Sales",
    productSales: "Product Sales",
    customerSales: "Customer Sales",
    itemPurchase: "Item Purchase",
    supplierReport: "Supplier Report",
    cashFlow: "Cash Flow",
    bankPayments: "Bank Payments",
    refunds: "Refunds & Returns",
    users: "Users",
    allUsers: "All Users",
    addUser: "Add User",
    roles: "Roles",
    stores: "Stores",
    allStores: "All Stores",
    addStore: "Add Store",
    posSystem: "POS SYSTEM",

    // Dashboard
    dashboardOverview: "DASHBOARD OVERVIEW",
    welcomeBack: "Welcome back,",
    liveBusinessSummary: "Live business summary",
    totalRevenue: "Total Revenue",
    totalPurchases: "Total Purchases",
    netProfit: "Net Profit",
    paidRevenue: "Paid Revenue",
    pendingDues: "Pending Dues",
    financialSnapshot: "Financial Snapshot",
    quickActions: "Quick Actions",
    recentSales: "Recent Sales",
    viewAll: "View All",
    revenue: "Revenue",
    profit: "Profit",
    loss: "Loss",
    collectedAmount: "Collected amount",
    customerDue: "Customer due",
    refresh: "Refresh",

    // Table Headers & Common
    invoice: "Invoice",
    customer: "Customer",
    amount: "Amount",
    paid: "Paid",
    due: "Due",
    status: "Status",
    date: "Date",
    action: "Action",
    search: "Search",
    loading: "Loading...",
    noData: "No data found",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    view: "View",
    print: "Print",
    download: "Download",
    filter: "Filter",
    all: "All",
    total: "Total",

    // Sales/POS
    items: "Items",
    subTotal: "Sub Total",
    discount: "Discount",
    tax: "Tax",
    grandTotal: "Grand Total",
    paymentMethod: "Payment Method",
    cash: "Cash",
    bank: "Bank",
    mobileBanking: "Mobile Banking",
    completeSale: "Complete Sale",
    walkInCustomer: "Walk-in Customer",
    selectProduct: "Select Product",
    quantity: "Quantity",
    price: "Price",
    stock: "Stock",

    // Inventory/Products
    productName: "Product Name",
    sku: "SKU",
    barcode: "Barcode",
    category: "Category",
    brand: "Brand",
    unit: "Unit",
    buyingPrice: "Buying Price",
    sellingPrice: "Selling Price",
    minStock: "Min Stock",
    description: "Description",
    image: "Image",

    // POS Specific
    searchProduct: "Search product by name or SKU...",
    remove: "Remove",
    loadingProducts: "Loading products...",
    noProductsFound: "No products found",
    saleItems: "Sale Items",
    noItemsAdded: "No items added yet. Search product above.",
    product: "Product",
    new: "New",
    noPhone: "No phone",
    searchCustomerPlaceholder: "Search customer or keep walk-in...",
    discountType: "Discount Type",
    percentage: "Percentage",
    fixed: "Fixed",
    discountValue: "Discount Value",
    vatTax: "VAT / Tax (%)",
    paidAmount: "Paid Amount",
    billSummary: "Bill Summary",
    change: "Change",
    savingSale: "Saving Sale...",
    generateInvoice: "Generate Invoice & Save",
    fullName: "Full name",
    customerType: "Customer Type",
    retail: "Retail",
    wholesale: "Wholesale",
    vip: "VIP",
    active: "Active",
    inactive: "Inactive",
    details: "Details",
    material: "Material",
    color: "Color",
    dimensions: "Dimensions",
    margin: "Margin",
    costPrice: "Cost Price",
    deleteProductQuestion: "Delete Product?",
    deleteProductWarning: "You're about to delete",
    inventoryValue: "Inventory Value",
    atSellingPrice: "At selling price",
    hiddenProducts: "Hidden products",
    availableGroups: "Available groups",
    searchProductPlaceholder: "Search by name, SKU, brand...",
    showing: "Showing",
    of: "of",
    editProduct: "Edit Product",
    deleting: "Deleting...",
    totalCustomers: "Total Customers",
    activeCustomers: "Active Customers",
    inactiveCustomers: "Inactive Customers",
    searchCustomer: "Search customer...",
    addCustomer: "Add Customer",
    noCustomersFound: "No customers found",
    removeCustomerQuestion: "Remove Customer?",
    removeCustomerWarning: "will be marked inactive.",
    removing: "Removing...",
    customerDetails: "Customer Details",
    creditLimit: "Credit Limit",
    totalSalesRecords: "Total sales records",
    saveChanges: "Save Changes",
    saving: "Saving...",
    type: "Type",
    credit: "Credit",
    totalSuppliers: "Total Suppliers",
    activeSuppliers: "Active Suppliers",
    inactiveSuppliers: "Inactive Suppliers",
    searchSupplier: "Search supplier...",
    addSupplier: "Add Supplier",
    noSuppliersFound: "No suppliers found",
    removeSupplierQuestion: "Remove Supplier?",
    removeSupplierWarning: "will be soft-deleted and marked inactive.",
    supplierDetails: "Supplier Details",
    gstNumber: "GST Number",
    paymentTerms: "Payment Terms",
    purchaseHistory: "Purchase History",
    totalPurchases: "Total purchases",
    supplierStatus: "Supplier Status",
    contactPerson: "Contact Person",
    supplierName: "Supplier Name",
    allSupplierRecords: "All supplier records",
    availableSuppliers: "Available suppliers",
    softDeletedSuppliers: "Soft-deleted suppliers",
    pendingApproval: "Pending Approval",
    totalPaid: "Total Paid",
    searchExpenses: "Search expenses...",
    addExpense: "Add Expense",
    noExpensesFound: "No expenses found",
    approve: "Approve",
    markPaid: "Mark Paid",
    approved: "Approved",
    paid: "Paid",
    cancelled: "Cancelled",
    allStatus: "All Status",
    method: "Method",
    addNewExpense: "Add New Expense",
    expenseTitle: "Expense Title",
    selectCategory: "Select Category",
    selectStore: "Select Store",
    general: "General",
    utility: "Utility",
    rent: "Rent",
    salary: "Salary",
    saveExpense: "Save Expense",
    expenseAddedSuccessfully: "Expense Added Successfully!",
    redirectingToList: "Redirecting to list...",
    notes: "Notes",
    inventoryRecords: "Inventory Records",
    totalQuantity: "Total Quantity",
    lowOutStock: "Low / Out Stock",
    stockValue: "Stock Value",
    createInventory: "Create Inventory",
    editInventory: "Edit Inventory",
    qty: "Qty",
    min: "Min",
    max: "Max",
    healthy: "Healthy",
    warning: "Warning",
    low: "Low",
    out: "Out",
    addInventory: "Add Inventory",
    noInventoryFound: "No inventory found",
    locationInStore: "Location In Store",
    valuationPrice: "Valuation Price",
    fullPreview: "Full Preview",
    quantityToAdd: "Quantity to Add",
    deleteInventoryQuestion: "Delete Inventory?",
    searchInventory: "Search product, SKU, store...",
    allStores: "All Stores",
    selectStore: "Select store",
    selectProduct: "Select product",
    totalCategories: "Total Categories",
    active: "Active",
    inactive: "Inactive",
    searchCategory: "Search category...",
    newCategory: "New Category",
    createCategory: "Create Category",
    editCategory: "Edit Category",
    categoryName: "Category Name",
    deleteCategoryQuestion: "Delete Category?",
    onlyNecessaryFields: "Only necessary fields are shown",
    activeCategory: "Active category",
    inactiveCategory: "Inactive category",
    noCategoriesFound: "No categories found",
    damageStock: "Damage Stock",
    reportDamage: "Report Damage",
    reportDamagedStock: "Report Damaged Stock",
    totalReports: "Total Reports",
    pendingReview: "Pending Review",
    totalLoss: "Total Loss",
    searchByProductSkuId: "Search by product, SKU, ID...",
    reported: "Reported",
    reviewed: "Reviewed",
    resolved: "Resolved",
    discarded: "Discarded",
    underReview: "Under Review",
    damageType: "Damage Type",
    damageDescription: "Damage Description",
    initialActionTaken: "Initial Action Taken",
    submitDamageReport: "Submit Damage Report",
    reporting: "Reporting...",
    reportedBy: "Reported By",
    actionTakenNotes: "Action Taken / Notes",
    review: "Review",
    resolve: "Resolve",
    discard: "Discard",
    waterDamage: "Water Damage",
    physicalDamage: "Physical Damage",
    defectiveProduct: "Defective Product",
    transitDamage: "Transit Damage",
    fireSmoke: "Fire/Smoke",
    customerReturn: "Customer Return",
    theftMissing: "Theft/Missing",
    pestInfestation: "Pest/Infestation",
    other: "Other",
    stockTransfer: "Stock Transfer",
    newTransfer: "New Transfer",
    newStockTransfer: "New Stock Transfer",
    totalTransfers: "Total Transfers",
    pendingApproval: "Pending Approval",
    inTransit: "In Transit",
    unitsMoved: "Units Moved",
    searchTransferProductSkuStore: "Search transfer, product, SKU, store...",
    sourceStore: "Source Store",
    destinationStore: "Destination Store",
    selectSource: "Select source",
    selectDestination: "Select destination",
    moveStockFromOneBranchToAnother: "Move stock from one branch to another",
    availableStock: "Available Stock",
    transferPreview: "Transfer Preview",
    initiateTransfer: "Initiate Transfer",
    bulkApprove: "Bulk Approve",
    sourceDestinationSameError: "Source and destination stores must be different",
    insufficientStock: "Insufficient stock",
    approve: "Approve",
    reject: "Reject",
    complete: "Complete",
    markAsInTransit: "Mark as In Transit",
    stockTransferDetails: "Stock Transfer Details",
    reportsAnalytics: "Reports & Analytics",
    comprehensiveDataAnalysis: "Comprehensive data analysis for your business",
    salesRevenue: "Sales & Revenue",
    purchasesSuppliers: "Purchases & Suppliers",
    financeExpenses: "Finance & Expenses",
    generalSales: "General Sales",
    overallSalesPerformance: "Overall sales performance and invoices",
    dailySales: "Daily Sales",
    summaryOfSalesSpecificDay: "Summary of sales for a specific day",
    productWiseSales: "Product-wise Sales",
    analyzeWhichProductsSelling: "Analyze which products are selling most",
    customerWiseSales: "Customer-wise Sales",
    salesDataAggregatedByCustomer: "Sales data aggregated by customer",
    salesProfitLoss: "Sales Profit/Loss",
    profitMarginsOnEachSale: "Profit margins on each sale",
    refundsReturns: "Refunds/Returns",
    trackSalesPurchaseReturns: "Track sales and purchase returns",
    purchaseReport: "Purchase Report",
    trackAllStockPurchases: "Track all stock purchases",
    itemWisePurchase: "Item-wise Purchase",
    purchasesGroupedByProducts: "Purchases grouped by products",
    supplierReport: "Supplier Report",
    overviewAllSuppliersDues: "Overview of all suppliers and dues",
    supplierItemAnalysis: "Supplier Item Analysis",
    productsSourcedFromSuppliers: "Products sourced from specific suppliers",
    supplierProfitability: "Supplier Profitability",
    profitAnalysisBySupplier: "Profit analysis by supplier sourcing",
    cashFlow: "Cash Flow",
    monitorCashInflowsOutflows: "Monitor cash inflows and outflows",
    bankPayments: "Bank Payments",
    reportAllBankTransactions: "Report of all bank-based transactions",
    expenseReport: "Expense Report",
    categorizedBusinessExpenses: "Categorized business expenses",
    inventoryValuation: "Inventory Valuation",
    currentStockLevelsValuation: "Current stock levels and valuation",
    addUser: "Add User",
    editUser: "Edit User",
    usernameRequired: "Username is required",
    usernameMinChars: "Username must be at least 3 characters",
    passwordMinChars: "Password must be at least 6 characters",
    fullNameRequired: "Full name is required",
    roleRequired: "Role is required",
    storeRequiredForSeller: "Store is required for Seller",
    zoneRequiredForManager: "Zone is required for Manager",
    userUpdated: "User Updated",
    userCreated: "User Created",
    userSavedSuccessfully: "has been saved successfully",
    viewUsers: "View Users",
    addAnother: "Add Another",
    loadingUser: "Loading user",
    createSystemAccountRoleBranch: "Create system account with role and branch access",
    assignStoreRequiredSeller: "Assign Store (Required for Seller)",
    assignZoneRequiredManager: "Assign Zone (Required for Manager)",
    activeAccount: "Active account",
    userPreview: "USER PREVIEW",
    fullSystemAccess: "Full system access",
    manageStoresInZone: "Manage stores in a zone",
    salesCustomerHandling: "Sales and customer handling",
    admin: "Admin",
    manager: "Manager",
    seller: "Seller",
    newPassword: "New Password",
    keepBlankToAvoidChange: "Keep blank to avoid change",
    allUsers: "All Users",
    manageAdminManagerSellerAccounts: "Manage admin, manager and seller accounts",
    totalUsers: "Total Users",
    admins: "Admins",
    searchNameUsernameEmailPhone: "Search name, username, email, phone...",
    allRoles: "All Roles",
    deleteUserConfirmTitle: "Delete User?",
    deleteUserConfirmDesc: "will be deleted. If user has sales/purchases, backend may block deletion.",
    userRoles: "User Roles",
    rolePermissionOverview: "Role permission overview for admin, manager and seller",
    adminDesc: "Full system access and user management permission.",
    managerDesc: "Store operation and inventory management permission.",
    sellerDesc: "POS, customer and basic stock visibility permission.",
    permCreateUpdateDeleteUsers: "Create, update and delete users",
    permManageProductsBranchesSuppliers: "Manage products, branches and suppliers",
    permApproveReturnsStockTransfer: "Approve returns and stock transfer",
    permViewSalesPurchasesReports: "View sales, purchases and financial reports",
    permCreateProductCategoryPurchase: "Create product, category and purchase",
    permManageInventoryStockTransfer: "Manage inventory and stock transfer",
    permViewSalesPurchaseReports: "View sales and purchase reports",
    permCreateSupplierCustomer: "Create supplier and customer",
    permCreateNewSales: "Create new sales",
    permViewCustomersSuppliers: "View customers and suppliers",
    permCheckStockAlerts: "Check stock alerts",
    permViewSaleHistoryStore: "View sale history assigned to store",
    backendRouteProtection: "Backend Route Protection",
    backendRouteProtectionDesc: "User APIs are protected by auth middleware and admin authorization. Only admin can create, update, toggle status and delete users.",
    salesReport: "Sales Report",
    analyzeSalesPerformance: "Analyze your sales performance",
    totalRevenue: "Total Revenue",
    totalReceived: "Total Received",
    totalOutstanding: "Total Outstanding",
    totalInvoices: "Total Invoices",
    printReport: "Print Report",
    invoice: "Invoice",
    paid: "Paid",
    noRecordsFoundPeriod: "No records found for this period",
    walkIn: "Walk-in",
    trackStockProcurementSupplierPayments: "Track stock procurement and supplier payments",
    totalPurchases: "Total Purchases",
    paidToSuppliers: "Paid to Suppliers",
    outstandingDebt: "Outstanding Debt",
    totalOrders: "Total Orders",
    poNumber: "PO Number",
    inventoryReport: "Inventory Report",
    stockLevelsAssetValuation: "Stock levels and asset valuation",
    totalStock: "Total Stock",
    stockValue: "Stock Value",
    lowStockItems: "Low Stock Items",
    productTypes: "Product Types",
    filterByStore: "Filter by Store",
    currentStock: "Current Stock",
    unitPrice: "Unit Price",
    totalValue: "Total Value",
    inStock: "In Stock",
    businessExpenditureAnalysis: "Business expenditure analysis",
    transactionCount: "Transaction Count",
    averageExpense: "Average Expense",
    topCategory: "Top Category",
    reference: "Reference",
    dailySalesReport: "Daily Sales Report",
    salesSummaryFor: "Sales summary for",
    totalDue: "Total Due",
    selectDate: "Select Date",
    noSalesFoundDate: "No sales found for this date",
    time: "Time",
    salesProfitLoss: "Sales Profit & Loss",
    detailedProfitAnalysisSale: "Detailed profit analysis for each sale",
    totalCost: "Total Cost",
    totalProfit: "Total Profit",
    avgMargin: "Avg Margin",
    revenue: "Revenue",
    cost: "Cost",
    profit: "Profit",
    margin: "Margin",
    bankPaymentReport: "Bank Payment Report",
    transactionsBankTransfersCards: "Transactions made via bank transfers/cards",
    accountInfo: "Account/Info",
    noBankPaymentsFound: "No bank payments found",
    installment: "Installment",
    cashFlowAnalysis: "Cash Flow Analysis",
    monitorCashInflowOutflow: "Monitor cash inflow and outflow",
    totalCashIn: "Total Cash In",
    totalCashOut: "Total Cash Out",
    netCashFlow: "Net Cash Flow",
    inflowDetails: "Inflow Details",
    outflowDetails: "Outflow Details",
    salePayments: "Sale Payments",
    installmentPayments: "Installment Payments",
    purchasePayments: "Purchase Payments",
    expensePayments: "Expense Payments",
    customerWiseSales: "Customer-wise Sales",
    analyzeSalesPerformanceCustomer: "Analyze sales performance by customer",
    productWiseSales: "Product-wise Sales",
    analyzeSalesPerformanceProduct: "Analyze sales performance by product",
    qtySold: "Qty Sold",
    refundsReturnsReport: "Refunds & Returns Report",
    trackSalesPurchaseReturns: "Track all sales and purchase returns",
    totalSalesRefunds: "Total Sales Refunds",
    totalPurchaseRefunds: "Total Purchase Refunds",
    salesReturns: "Sales Returns",
    purchaseReturns: "Purchase Returns",
    refund: "Refund",
    noSalesReturnsFound: "No sales returns found",
    noPurchaseReturnsFound: "No purchase returns found",
    supplierPerformanceReport: "Supplier Performance Report",
    overviewSupplierTransactionsDues: "Overview of supplier transactions and dues",
    contactPerson: "Contact Person",
    purchases: "Purchases",
    balanceDue: "Balance Due",
    noSuppliersFound: "No suppliers found",
    supplierProfitabilityAnalysis: "Supplier Profitability Analysis",
    profitMarginsProductsSourcedSuppliers: "Profit margins on products sourced from specific suppliers",
    totalNetProfit: "Total Net Profit",
    pleaseSelectSupplierReport: "Please select a supplier to view the report",
    noSalesFoundSupplierProducts: "No sales found for products from this supplier",
    supplierItemAnalysis: "Supplier Item Analysis",
    trackProductsSourcedSuppliers: "Track products sourced from different suppliers",
    itemWisePurchaseReport: "Item-wise Purchase Report",
    analyzeStockPurchasesProduct: "Analyze stock purchases by product",
    qtyPurchased: "Qty Purchased",
    dashboardOverview: "Dashboard Overview",
    welcomeBack: "Welcome Back",
    liveBusinessSummary: "Live business summary",
    collectedAmount: "Collected amount",
    customerDue: "Customer due",
    lowStock: "low stock",
    financialSnapshot: "Financial Snapshot",
    revenuePurchaseExpenseProfitComparison: "Revenue, purchase, expense and profit comparison",
    quickActions: "Quick Actions",
    frequentlyUsedOperations: "Frequently used operations",
    createPosInvoice: "Create POS invoice",
    itemsNeedAttention: "items need attention",
    receiveNewStock: "Receive new stock",
    viewReportsInvoices: "View reports & invoices",
    recentSales: "Recent Sales",
    loadingRecentSales: "Loading recent sales...",
    searchProduct: "Search Product",
    saleItems: "Sale Items",
    noItemsAdded: "No items added to sale",
    searchCustomerPlaceholder: "Search customer...",
    discountType: "Discount Type",
    percentage: "Percentage",
    fixed: "Fixed",
    discountValue: "Discount Value",
    vatTax: "VAT/TAX (%)",
    paymentMethod: "Payment Method",
    cash: "Cash",
    bank: "Bank",
    card: "Card",
    mobileBanking: "Mobile Banking",
    paidAmount: "Paid Amount",
    notes: "Notes",
    subtotal: "Subtotal",
    discount: "Discount",
    vatAmount: "VAT Amount",
    change: "Change",
    completeSale: "Complete Sale",
    saving: "Saving...",
    customerNameRequired: "Customer name is required",
    failedCreateCustomer: "Failed to create customer",
    addOneProduct: "Please add at least one product",
    paidAmountNegative: "Paid amount cannot be negative",
    saleFailed: "Sale failed",
    paymentAndDiscount: "PAYMENT & DISCOUNT",
    noCategory: "No Category",
    billSummary: "Bill Summary",
    subTotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    generateInvoice: "Generate Invoice",
    savingSale: "Saving Sale...",
    cancel: "Cancel",
    retail: "Retail",
    wholesale: "Wholesale",
    vip: "VIP",
    totalSales: "Total Sales",
    totalPaid: "Total Paid",
    totalDue: "Total Due",
    invoices: "Invoices",
    searchInvoiceCustomerStore: "Search invoice, customer, store...",
    allStatus: "All Status",
    selected: "selected",
    exportCsv: "Export CSV",
    invoiceNo: "Invoice No.",
    seller: "Seller",
    actions: "Actions",
    loadingSales: "Loading sales...",
    noSaleHistoryFound: "No sale history found",
    showPdf: "Show PDF",
    newPurchase: "New Purchase",
    purchaseCreated: "Purchase Created",
    poNumber: "PO Number",
    createAnother: "Create Another",
    selectStore: "Select store",
    selectSupplier: "Select supplier",
    expectedDelivery: "Expected Delivery",
    receivedDate: "Received Date",
    selectProduct: "Select product",
    ordered: "Ordered",
    received: "Received",
    unitCost: "Unit Cost",
    itemDiscount: "Item Discount",
    finalUnitCost: "Final Unit Cost",
    payment: "Payment",
    taxAmount: "Tax Amount",
    paymentStatus: "Payment Status",
    paymentTerms: "Payment Terms",
    summary: "Summary",
    creating: "Creating...",
    createPurchase: "Create Purchase",
    storeRequired: "Store is required",
    supplierRequired: "Supplier is required",
    everyItemNeedsProduct: "Every item needs a product",
    qtyOrderedPositive: "Quantity ordered must be greater than 0",
    qtyReceivedNegative: "Quantity received cannot be negative",
    unitCostRequired: "Unit cost is required",
    totalPurchase: "Total Purchase",
    records: "Records",
    searchPoSupplierStore: "Search PO, supplier, store...",
    loadingPurchases: "Loading purchases...",
    noPurchaseHistoryFound: "No purchase history found",
    totalReturns: "Total Returns",
    refundAmount: "Refund Amount",
    searchReturnPoProduct: "Search return, PO, product...",
    newReturn: "New Return",
    loadingPurchaseReturns: "Loading purchase returns...",
    noPurchaseReturnFound: "No purchase return found",
    returnId: "Return ID",
    reason: "Reason",
    complete: "Complete",
    createPurchaseReturn: "Create Purchase Return",
    searchPo: "Search PO",
    searchPoSupplierPlaceholder: "Search PO/supplier...",
    selectPurchasedProduct: "Select purchased product",
    refund: "Refund",
    purchaseReturnDetails: "Purchase Return Details",
    selectPurchaseFirst: "Select purchase first",
    selectProductFirst: "Select product first",
    quantityRequired: "Quantity required",
    inventoryRecords: "Inventory Records",
    totalQuantity: "Total Quantity",
    lowOutStock: "Low/Out of Stock",
    stockValue: "Stock Value",
    searchInventory: "Search product, SKU, store...",
    allStores: "All Stores",
    addInventory: "Add Inventory",
    noInventoryFound: "No inventory found",
    createInventory: "Create Inventory",
    unknownProduct: "Unknown Product",
    unknownStore: "Unknown Store",
    noLocation: "No location",
    editInventory: "Edit Inventory",
    valuationPrice: "Valuation Price",
    locationInStore: "Location in Store",
    fullPreview: "Full Preview",
    deleteInventoryQuestion: "Delete this inventory record?",
    addingStockFor: "Adding stock for",
    quantityToAdd: "Quantity to Add",
    enterQuantity: "Enter quantity",
    at: "at",
    from: "from",
    saving: "Saving...",
    saveChanges: "Save Changes",
    deleting: "Deleting...",
    totalTransfers: "Total Transfers",
    pendingApproval: "Pending Approval",
    inTransit: "In Transit",
    unitsMoved: "Units Moved",
    searchTransferProductSkuStore: "Search transfer, product, SKU, store...",
    newTransfer: "New Transfer",
    newStockTransfer: "New Stock Transfer",
    moveStockFromOneBranchToAnother: "Move stock from one branch to another",
    sourceStore: "Source Store",
    destinationStore: "Destination Store",
    selectSource: "Select Source",
    selectDestination: "Select Destination",
    writeProductNameOrSku: "Write product name or SKU",
    selectSourceStoreFirst: "Select source store first",
    noProductsWithStockInThisStore: "No products with stock in this store",
    transferPreview: "Transfer Preview",
    initiateTransfer: "Initiate Transfer",
    bulkApprove: "Bulk Approve",
    availableStock: "Available Stock",
    sourceDestinationSameError: "Source and destination store cannot be the same",
    quantityMustBePositive: "Quantity must be positive",
    insufficientStock: "Insufficient stock",
    ship: "Ship",
    receive: "Receive",
    done: "Done",
    id: "ID",
    source: "Source",
    dest: "Dest",
    createFirstTransfer: "Create First Transfer",
    totalReports: "Total Reports",
    pendingReview: "Pending Review",
    totalLoss: "Total Loss",
    searchByProductSkuId: "Search by product, SKU, ID...",
    reported: "Reported",
    reviewed: "Reviewed",
    discarded: "Discarded",
    waterDamage: "Water Damage",
    physicalDamage: "Physical Damage",
    defectiveProduct: "Defective Product",
    transitDamage: "Transit Damage",
    fireSmoke: "Fire/Smoke",
    theftMissing: "Theft/Missing",
    pestInfestation: "Pest/Infestation",
    reportDamagedStock: "Report Damaged Stock",
    documentDamageIncident: "Document a damage or loss incident",
    quantityDamaged: "Quantity Damaged",
    lossAmount: "Loss Amount",
    estimatedCostLoss: "Estimated cost/loss",
    damageType: "Damage Type",
    damageDescription: "Damage Description",
    describeDamageInDetail: "Describe the damage in detail",
    initialActionTaken: "Initial Action Taken",
    anyImmediateActionTaken: "Any immediate action taken?",
    reporting: "Reporting...",
    submitDamageReport: "Submit Damage Report",
    damageReportDetails: "Damage Report Details",
    dateReported: "Date Reported",
    reportedBy: "Reported By",
    actionTakenNotes: "Action Taken Notes",
    review: "Review",
    resolve: "Resolve",
    discard: "Discard",
    unit: "Unit",
    units: "Units",
    stockAlert: "Stock Alert",
    stockAlertSubtitle: "Low stock, out of stock and overstock products from API",
    refresh: "Refresh",
    lowStock: "Low Stock",
    outOfStock: "Out of Stock",
    overstock: "Overstock",
    showing: "Showing",
    searchProductSkuStore: "Search product, SKU, store...",
    lowOutStockAlert: "Low / Out Stock",
    loadingStockAlerts: "Loading stock alerts...",
    noOverstockAlerts: "No overstock alerts found",
    noLowStockAlerts: "No low stock alerts found",
    extra: "Extra",
  },

  bn: {
    dashboard: "ড্যাশবোর্ড",
    newSale: "নতুন বিক্রি",
    purchase: "ক্রয়",
    notifications: "নোটিফিকেশন",
    live: "লাইভ",
    viewStockAlerts: "স্টক অ্যালার্ট দেখুন",
    totalSales: "মোট বিক্রি",
    purchases: "মোট ক্রয়",
    dueAmount: "বাকি টাকা",
    lowStockItems: "লো স্টক আইটেম",
    sales: "বিক্রি",
    cost: "খরচ",
    pending: "বাকি",
    alert: "অ্যালার্ট",
    myProfile: "আমার প্রোফাইল",
    reports: "রিপোর্ট",
    settings: "সেটিংস",
    signOut: "সাইন আউট",
    noStore: "স্টোর নেই",
    noRole: "রোল নেই",
    language: "ভাষা",
    english: "English",
    bangla: "বাংলা",
    // Side Bar
    saleHistory: "বিক্রির হিস্টোরি",
    saleReturns: "বিক্রি রিটার্ন",
    installments: "কিস্তি",
    newPurchase: "নতুন ক্রয়",
    purchaseHistory: "ক্রয় হিস্টোরি",
    purchaseReturns: "ক্রয় রিটার্ন",
    inventory: "ইনভেন্টরি",
    stockOverview: "স্টক ওভারভিউ",
    lowStockAlert: "লো স্টক অ্যালার্ট",
    stockTransfer: "স্টক ট্রান্সফার",
    damageStock: "ড্যামেজ স্টক",
    products: "পণ্য",
    allProducts: "সব পণ্য",
    addProduct: "পণ্য যোগ করুন",
    categories: "ক্যাটাগরি",
    customers: "কাস্টমার",
    allCustomers: "সব কাস্টমার",
    addCustomer: "কাস্টমার যোগ করুন",
    suppliers: "সাপ্লায়ার",
    allSuppliers: "সব সাপ্লায়ার",
    addSupplier: "সাপ্লায়ার যোগ করুন",
    expenses: "খরচ",
    allExpenses: "সব খরচ",
    addExpense: "খরচ যোগ করুন",
    yearlyTracking: "বার্ষিক ট্র্যাকিং",
    salesReport: "বিক্রি রিপোর্ট",
    purchaseReport: "ক্রয় রিপোর্ট",
    inventoryReport: "ইনভেন্টরি রিপোর্ট",
    expenseReport: "খরচ রিপোর্ট",
    profitLoss: "লাভ-ক্ষতি",
    reportsOverview: "রিপোর্ট ওভারভিউ",
    dailySales: "দৈনিক বিক্রি",
    productSales: "পণ্য ভিত্তিক বিক্রি",
    customerSales: "কাস্টমার ভিত্তিক বিক্রি",
    itemPurchase: "আইটেম ভিত্তিক ক্রয়",
    supplierReport: "সাপ্লায়ার রিপোর্ট",
    cashFlow: "ক্যাশ ফ্লো",
    bankPayments: "ব্যাংক পেমেন্ট",
    refunds: "রিফান্ড ও রিটার্ন",
    users: "ইউজার",
    allUsers: "সব ইউজার",
    addUser: "ইউজার যোগ করুন",
    roles: "রোল",
    stores: "স্টোর",
    allStores: "সব স্টোর",
    addStore: "স্টোর যোগ করুন",
    posSystem: "পিওএস সিস্টেম",

    // Dashboard
    dashboardOverview: "ড্যাশবোর্ড ওভারভিউ",
    welcomeBack: "স্বাগতম,",
    liveBusinessSummary: "লাইভ ব্যবসা সারাংশ",
    totalRevenue: "মোট আয়",
    totalPurchases: "মোট ক্রয়",
    netProfit: "নিট লাভ",
    paidRevenue: "পরিশোধিত আয়",
    pendingDues: "বাকি পাওনা",
    financialSnapshot: "আর্থিক চিত্র",
    quickActions: "দ্রুত অ্যাকশন",
    recentSales: "সাম্প্রতিক বিক্রি",
    viewAll: "সব দেখুন",
    revenue: "আয়",
    profit: "লাভ",
    loss: "ক্ষতি",
    collectedAmount: "সংগৃহীত টাকা",
    customerDue: "কাস্টমার বাকি",
    refresh: "রিফ্রেশ",

    // Table Headers & Common
    invoice: "ইনভয়েস",
    customer: "কাস্টমার",
    amount: "পরিমাণ",
    paid: "পেমেন্ট",
    due: "বাকি",
    status: "অবস্থা",
    date: "তারিখ",
    action: "অ্যাকশন",
    search: "অনুসন্ধান",
    loading: "লোডিং...",
    noData: "কোন তথ্য পাওয়া যায়নি",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    edit: "সম্পাদনা",
    delete: "মুছে ফেলুন",
    view: "দেখুন",
    print: "প্রিন্ট",
    download: "ডাউনলোড",
    filter: "ফিল্টার",
    all: "সব",
    total: "মোট",

    // Sales/POS
    items: "আইটেম",
    subTotal: "সাব টোটাল",
    discount: "ডিসকাউন্ট",
    tax: "ট্যাক্স",
    grandTotal: "সর্বমোট",
    paymentMethod: "পেমেন্ট পদ্ধতি",
    cash: "নগদ",
    bank: "ব্যাংক",
    mobileBanking: "মোবাইল ব্যাংকিং",
    completeSale: "বিক্রি সম্পন্ন করুন",
    walkInCustomer: "সাধারণ কাস্টমার",
    selectProduct: "পণ্য নির্বাচন করুন",
    quantity: "পরিমাণ",
    price: "দাম",
    stock: "স্টক",

    // Inventory/Products
    productName: "পণ্যের নাম",
    sku: "এসকেইউ (SKU)",
    barcode: "বারকোড",
    category: "ক্যাটাগরি",
    brand: "ব্র্যান্ড",
    unit: "ইউনিট",
    buyingPrice: "ক্রয় মূল্য",
    sellingPrice: "বিক্রয় মূল্য",
    minStock: "সর্বনিম্ন স্টক",
    description: "বিবরণ",
    image: "ছবি",

    // POS Specific
    searchProduct: "নাম বা এসকেইউ দিয়ে পণ্য খুঁজুন...",
    remove: "মুছুন",
    loadingProducts: "পণ্য লোড হচ্ছে...",
    noProductsFound: "কোন পণ্য পাওয়া যায়নি",
    saleItems: "বিক্রয় আইটেম",
    noItemsAdded: "এখনো কোন আইটেম যোগ করা হয়নি। উপরে পণ্য খুঁজুন।",
    product: "পণ্য",
    new: "নতুন",
    noPhone: "ফোন নম্বর নেই",
    searchCustomerPlaceholder: "কাস্টমার খুঁজুন বা সাধারণ কাস্টমার হিসেবে রাখুন...",
    discountType: "ডিসকাউন্ট টাইপ",
    percentage: "শতকরা (%)",
    fixed: "স্থির (Fixed)",
    discountValue: "ডিসকাউন্ট মূল্য",
    vatTax: "ভ্যাট / ট্যাক্স (%)",
    paidAmount: "পরিশোধিত টাকা",
    billSummary: "বিল সারাংশ",
    change: "ফেরত",
    savingSale: "বিক্রি সেভ হচ্ছে...",
    generateInvoice: "ইনভয়েস তৈরি এবং সেভ করুন",
    fullName: "পুরো নাম",
    customerType: "কাস্টমার টাইপ",
    retail: "খুচরা",
    wholesale: "পাইকারি",
    vip: "ভিআইপি",
    active: "সক্রিয়",
    inactive: "নিষ্ক্রিয়",
    details: "বিস্তারিত",
    material: "উপাদান",
    color: "রঙ",
    dimensions: "মাপ (Dimensions)",
    margin: "মার্জিন",
    costPrice: "ক্রয় মূল্য",
    deleteProductQuestion: "পণ্যটি কি মুছে ফেলবেন?",
    deleteProductWarning: "আপনি মুছে ফেলতে যাচ্ছেন",
    inventoryValue: "ইনভেন্টরি মূল্য",
    atSellingPrice: "বিক্রয় মূল্যে",
    hiddenProducts: "লুকানো পণ্য",
    availableGroups: "উপলব্ধ গ্রুপ",
    searchProductPlaceholder: "নাম, এসকেইউ, ব্র্যান্ড দিয়ে খুঁজুন...",
    showing: "দেখাচ্ছে",
    of: "এর মধ্যে",
    editProduct: "পণ্য সম্পাদনা করুন",
    deleting: "মুছে ফেলা হচ্ছে...",
    totalCustomers: "মোট কাস্টমার",
    activeCustomers: "সক্রিয় কাস্টমার",
    inactiveCustomers: "নিষ্ক্রিয় কাস্টমার",
    searchCustomer: "কাস্টমার খুঁজুন...",
    addCustomer: "কাস্টমার যোগ করুন",
    noCustomersFound: "কোন কাস্টমার পাওয়া যায়নি",
    removeCustomerQuestion: "কাস্টমার মুছে ফেলবেন?",
    removeCustomerWarning: "নিষ্ক্রিয় হিসেবে চিহ্নিত করা হবে।",
    removing: "মুছে ফেলা হচ্ছে...",
    customerDetails: "কাস্টমার বিস্তারিত",
    creditLimit: "ক্রেডিট লিমিট",
    totalSalesRecords: "মোট বিক্রয় রেকর্ড",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    saving: "সংরক্ষণ হচ্ছে...",
    type: "ধরণ",
    credit: "ক্রেডিট",
    totalSuppliers: "মোট সাপ্লায়ার",
    activeSuppliers: "সক্রিয় সাপ্লায়ার",
    inactiveSuppliers: "নিষ্ক্রিয় সাপ্লায়ার",
    searchSupplier: "সাপ্লায়ার খুঁজুন...",
    addSupplier: "সাপ্লায়ার যোগ করুন",
    noSuppliersFound: "কোন সাপ্লায়ার পাওয়া যায়নি",
    removeSupplierQuestion: "সাপ্লায়ার মুছে ফেলবেন?",
    removeSupplierWarning: "সফট-ডিলিট করা হবে এবং নিষ্ক্রিয় হিসেবে চিহ্নিত হবে।",
    supplierDetails: "সাপ্লায়ার বিস্তারিত",
    gstNumber: "জিএসটি নম্বর",
    paymentTerms: "পেমেন্ট টার্মস",
    purchaseHistory: "ক্রয় ইতিহাস",
    totalPurchases: "মোট ক্রয়",
    supplierStatus: "সাপ্লায়ার স্ট্যাটাস",
    contactPerson: "যোগাযোগকারী ব্যক্তি",
    supplierName: "সাপ্লায়ার নাম",
    allSupplierRecords: "সব সাপ্লায়ার রেকর্ড",
    availableSuppliers: "উপলব্ধ সাপ্লায়ার",
    softDeletedSuppliers: "সফট-ডিলিট করা সাপ্লায়ার",
    pendingApproval: "অনুমোদনের অপেক্ষায়",
    totalPaid: "মোট পরিশোধিত",
    searchExpenses: "খরচ খুঁজুন...",
    addExpense: "খরচ যোগ করুন",
    noExpensesFound: "কোন খরচ পাওয়া যায়নি",
    approve: "অনুমোদন করুন",
    markPaid: "পরিশোধিত হিসেবে চিহ্নিত করুন",
    approved: "অনুমোদিত",
    paid: "পরিশোধিত",
    cancelled: "বাতিল",
    allStatus: "সব স্ট্যাটাস",
    method: "পদ্ধতি",
    addNewExpense: "নতুন খরচ যোগ করুন",
    expenseTitle: "খরচের শিরোনাম",
    selectCategory: "ক্যাটাগরি নির্বাচন করুন",
    selectStore: "স্টোর নির্বাচন করুন",
    general: "সাধারণ",
    utility: "ইউটিলিটি",
    rent: "ভাড়া",
    salary: "বেতন",
    saveExpense: "খরচ সংরক্ষণ করুন",
    expenseAddedSuccessfully: "খরচ সফলভাবে যোগ করা হয়েছে!",
    redirectingToList: "তালিকায় ফিরিয়ে নেওয়া হচ্ছে...",
    notes: "নোট",
    inventoryRecords: "ইনভেন্টরি রেকর্ড",
    totalQuantity: "মোট পরিমাণ",
    lowOutStock: "কম / স্টক নেই",
    stockValue: "স্টক মূল্য",
    createInventory: "ইনভেন্টরি তৈরি করুন",
    editInventory: "ইনভেন্টরি পরিবর্তন করুন",
    qty: "পরিমাণ",
    min: "ন্যূনতম",
    max: "সর্বোচ্চ",
    healthy: "পর্যাপ্ত",
    warning: "সতর্কতা",
    low: "কম স্টক",
    out: "স্টক নেই",
    addInventory: "ইনভেন্টরি যোগ করুন",
    noInventoryFound: "কোন ইনভেন্টরি পাওয়া যায়নি",
    locationInStore: "স্টোরের অবস্থান",
    valuationPrice: "মূল্যায়ন মূল্য",
    fullPreview: "সম্পূর্ণ প্রিভিউ",
    quantityToAdd: "যোগ করার পরিমাণ",
    deleteInventoryQuestion: "ইনভেন্টরি মুছে ফেলবেন?",
    searchInventory: "পণ্য, SKU, স্টোর দিয়ে খুঁজুন...",
    allStores: "সব স্টোর",
    selectStore: "স্টোর নির্বাচন করুন",
    selectProduct: "পণ্য নির্বাচন করুন",
    totalCategories: "মোট ক্যাটাগরি",
    active: "সক্রিয়",
    inactive: "নিষ্ক্রিয়",
    searchCategory: "ক্যাটাগরি খুঁজুন...",
    newCategory: "নতুন ক্যাটাগরি",
    createCategory: "ক্যাটাগরি তৈরি করুন",
    editCategory: "ক্যাটাগরি পরিবর্তন করুন",
    categoryName: "ক্যাটাগরির নাম",
    deleteCategoryQuestion: "ক্যাটাগরি মুছে ফেলবেন?",
    onlyNecessaryFields: "শুধুমাত্র প্রয়োজনীয় তথ্য দেখানো হয়েছে",
    activeCategory: "সক্রিয় ক্যাটাগরি",
    inactiveCategory: "নিষ্ক্রিয় ক্যাটাগরি",
    noCategoriesFound: "কোন ক্যাটাগরি পাওয়া যায়নি",
    damageStock: "ক্ষতিগ্রস্ত স্টক",
    reportDamage: "ক্ষতি রিপোর্ট করুন",
    reportDamagedStock: "ক্ষতিগ্রস্ত স্টকের রিপোর্ট করুন",
    totalReports: "মোট রিপোর্ট",
    pendingReview: "রিভিউ অপেক্ষারত",
    totalLoss: "মোট লোকসান",
    searchByProductSkuId: "পণ্য, SKU, ID দিয়ে খুঁজুন...",
    reported: "রিপোর্ট করা হয়েছে",
    reviewed: "রিভিউ করা হয়েছে",
    resolved: "সমাধান করা হয়েছে",
    discarded: "বাতিল করা হয়েছে",
    underReview: "রিভিউ চলছে",
    damageType: "ক্ষতির ধরণ",
    damageDescription: "ক্ষতির বিবরণ",
    initialActionTaken: "প্রাথমিক ব্যবস্থা",
    submitDamageReport: "ক্ষতির রিপোর্ট জমা দিন",
    reporting: "রিপোর্ট করা হচ্ছে...",
    reportedBy: "রিপোর্ট করেছেন",
    actionTakenNotes: "গৃহীত ব্যবস্থা / নোট",
    review: "রিভিউ করুন",
    resolve: "সমাধান করুন",
    discard: "বাতিল করুন",
    waterDamage: "পানি দ্বারা ক্ষতি",
    physicalDamage: "শারীরিক ক্ষতি",
    defectiveProduct: "ত্রুটিপূর্ণ পণ্য",
    transitDamage: "পরিবহনকালীন ক্ষতি",
    fireSmoke: "আগুন/ধোঁয়া",
    customerReturn: "গ্রাহকের ফেরত",
    theftMissing: "চুরি/হারিয়ে যাওয়া",
    pestInfestation: "কীটপতঙ্গ দ্বারা ক্ষতি",
    other: "অন্যান্য",
    stockTransfer: "স্টক ট্রান্সফার",
    newTransfer: "নতুন ট্রান্সফার",
    newStockTransfer: "নতুন স্টক ট্রান্সফার",
    totalTransfers: "মোট ট্রান্সফার",
    pendingApproval: "অনুমোদনের অপেক্ষায়",
    inTransit: "পরিবহন চলছে",
    unitsMoved: "স্থানান্তরিত ইউনিট",
    searchTransferProductSkuStore: "ট্রান্সফার, পণ্য, SKU, স্টোর দিয়ে খুঁজুন...",
    sourceStore: "উৎস স্টোর",
    destinationStore: "গন্তব্য স্টোর",
    selectSource: "উৎস নির্বাচন করুন",
    selectDestination: "গন্তব্য নির্বাচন করুন",
    moveStockFromOneBranchToAnother: "এক শাখা থেকে অন্য শাখায় স্টক সরান",
    availableStock: "মজুদ স্টক",
    transferPreview: "ট্রান্সফার প্রিভিউ",
    initiateTransfer: "ট্রান্সফার শুরু করুন",
    bulkApprove: "একসাথে অনুমোদন",
    sourceDestinationSameError: "উৎস এবং গন্তব্য স্টোর ভিন্ন হতে হবে",
    insufficientStock: "অপর্যাপ্ত স্টক",
    approve: "অনুমোদন করুন",
    reject: "প্রত্যাখ্যান করুন",
    complete: "সম্পন্ন করুন",
    markAsInTransit: "পরিবহন হিসেবে চিহ্নিত করুন",
    stockTransferDetails: "স্টক ট্রান্সফার বিবরণ",
    reportsAnalytics: "রিপোর্ট এবং অ্যানালিটিক্স",
    comprehensiveDataAnalysis: "আপনার ব্যবসার জন্য বিস্তারিত তথ্য বিশ্লেষণ",
    salesRevenue: "বিক্রয় এবং রাজস্ব",
    purchasesSuppliers: "ক্রয় এবং সরবরাহকারী",
    financeExpenses: "অর্থায়ন এবং ব্যয়",
    generalSales: "সাধারণ বিক্রয়",
    overallSalesPerformance: "সামগ্রিক বিক্রয় কর্মক্ষমতা এবং ইনভয়েস",
    dailySales: "দৈনিক বিক্রয়",
    summaryOfSalesSpecificDay: "একটি নির্দিষ্ট দিনের বিক্রয়ের সারাংশ",
    productWiseSales: "পণ্য-ভিত্তিক বিক্রয়",
    analyzeWhichProductsSelling: "কোন পণ্যগুলি সবচেয়ে বেশি বিক্রি হচ্ছে তা বিশ্লেষণ করুন",
    customerWiseSales: "গ্রাহক-ভিত্তিক বিক্রয়",
    salesDataAggregatedByCustomer: "গ্রাহক অনুযায়ী একত্রিত বিক্রয় তথ্য",
    salesProfitLoss: "বিক্রয় লাভ/ক্ষতি",
    profitMarginsOnEachSale: "প্রতিটি বিক্রয়ের উপর লাভের মার্জিন",
    refundsReturns: "ফেরত/রিটার্ন",
    trackSalesPurchaseReturns: "বিক্রয় এবং ক্রয় রিটার্ন ট্র্যাক করুন",
    purchaseReport: "ক্রয় রিপোর্ট",
    trackAllStockPurchases: "সমস্ত স্টক ক্রয় ট্র্যাক করুন",
    itemWisePurchase: "পণ্য-ভিত্তিক ক্রয়",
    purchasesGroupedByProducts: "পণ্য অনুযায়ী একত্রিত ক্রয়",
    supplierReport: "সরবরাহকারী রিপোর্ট",
    overviewAllSuppliersDues: "সমস্ত সরবরাহকারী এবং বকেয়া টাকার ওভারভিউ",
    supplierItemAnalysis: "নির্দিষ্ট সরবরাহকারীদের থেকে সংগ্রহ করা পণ্য",
    productsSourcedFromSuppliers: "সরবরাহকারীদের থেকে প্রাপ্ত পণ্য",
    supplierProfitability: "সরবরাহকারী লাভজনকতা",
    profitAnalysisBySupplier: "সরবরাহকারী অনুযায়ী লাভ বিশ্লেষণ",
    cashFlow: "ক্যাশ ফ্লো",
    monitorCashInflowsOutflows: "নগদ প্রবাহ এবং বহিঃপ্রবাহ পর্যবেক্ষণ করুন",
    bankPayments: "ব্যাংক পেমেন্ট",
    reportAllBankTransactions: "সমস্ত ব্যাংক ভিত্তিক লেনদেনের রিপোর্ট",
    expenseReport: "ব্যয় রিপোর্ট",
    categorizedBusinessExpenses: "বিভাগীয় ব্যবসায়িক ব্যয়",
    inventoryValuation: "ইনভেন্টরি মূল্যায়ন",
    currentStockLevelsValuation: "বর্তমান স্টকের পরিমাণ এবং মূল্যায়ন",
    addUser: "ইউজার যোগ করুন",
    editUser: "ইউজার এডিট করুন",
    usernameRequired: "ইউজার নেম প্রয়োজন",
    usernameMinChars: "ইউজার নেম কমপক্ষে ৩ অক্ষরের হতে হবে",
    passwordMinChars: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে",
    fullNameRequired: "পূর্ণ নাম প্রয়োজন",
    roleRequired: "রোল প্রয়োজন",
    storeRequiredForSeller: "সেলার-এর জন্য স্টোর প্রয়োজন",
    zoneRequiredForManager: "ম্যানেজার-এর জন্য জোন প্রয়োজন",
    userUpdated: "ইউজার আপডেট করা হয়েছে",
    userCreated: "ইউজার তৈরি করা হয়েছে",
    userSavedSuccessfully: "সফলভাবে সেভ করা হয়েছে",
    viewUsers: "ইউজার তালিকা",
    addAnother: "আরও যোগ করুন",
    loadingUser: "ইউজার লোড হচ্ছে",
    createSystemAccountRoleBranch: "রোল এবং শাখা অ্যাক্সেস সহ সিস্টেম অ্যাকাউন্ট তৈরি করুন",
    assignStoreRequiredSeller: "স্টোর বরাদ্দ করুন (সেলারের জন্য প্রয়োজন)",
    assignZoneRequiredManager: "জোন বরাদ্দ করুন (ম্যানেজারের জন্য প্রয়োজন)",
    activeAccount: "সক্রিয় অ্যাকাউন্ট",
    userPreview: "ইউজার প্রিভিউ",
    fullSystemAccess: "পুরো সিস্টেম অ্যাক্সেস",
    manageStoresInZone: "জোনের স্টোরগুলো পরিচালনা করুন",
    salesCustomerHandling: "বিক্রয় এবং গ্রাহক পরিচালনা",
    admin: "এডমিন",
    manager: "ম্যানেজার",
    seller: "সেলার",
    newPassword: "নতুন পাসওয়ার্ড",
    keepBlankToAvoidChange: "পরিবর্তন না করতে চাইলে ফাঁকা রাখুন",
    allUsers: "সমস্ত ইউজার",
    manageAdminManagerSellerAccounts: "অ্যাডমিন, ম্যানেজার এবং সেলার অ্যাকাউন্ট পরিচালনা করুন",
    totalUsers: "মোট ইউজার",
    admins: "অ্যাডমিনগণ",
    searchNameUsernameEmailPhone: "নাম, ইউজারনেম, ইমেল, ফোন দিয়ে খুঁজুন...",
    allRoles: "সব রোল",
    deleteUserConfirmTitle: "ইউজার ডিলিট করবেন?",
    deleteUserConfirmDesc: "ডিলিট করা হবে। যদি ইউজারের কোনো সেলস/পারচেজ থাকে, তবে ব্যাকএন্ড ডিলিট করতে বাধা দিতে পারে।",
    userRoles: "ইউজার রোল",
    rolePermissionOverview: "অ্যাডমিন, ম্যানেজার এবং সেলারে রোল এবং পারমিশন ওভারভিউ",
    adminDesc: "পুরো সিস্টেম অ্যাক্সেস এবং ইউজার পরিচালনা করার অনুমতি।",
    managerDesc: "স্টোর পরিচালনা এবং ইনভেন্টরি পরিচালনা করার অনুমতি।",
    sellerDesc: "পিওএস, গ্রাহক এবং মৌলিক স্টক দেখার অনুমতি।",
    permCreateUpdateDeleteUsers: "ইউজার তৈরি, আপডেট এবং ডিলিট করা",
    permManageProductsBranchesSuppliers: "পণ্য, শাখা এবং সরবরাহকারী পরিচালনা",
    permApproveReturnsStockTransfer: "রিটার্ন এবং স্টক ট্রান্সফার অনুমোদন",
    permViewSalesPurchasesReports: "বিক্রয়, ক্রয় এবং আর্থিক রিপোর্ট দেখা",
    permCreateProductCategoryPurchase: "পণ্য, বিভাগ এবং ক্রয় তৈরি",
    permManageInventoryStockTransfer: "ইনভেন্টরি এবং স্টক ট্রান্সফার পরিচালনা",
    permViewSalesPurchaseReports: "বিক্রয় এবং ক্রয় রিপোর্ট দেখা",
    permCreateSupplierCustomer: "সরবরাহকারী এবং গ্রাহক তৈরি",
    permCreateNewSales: "নতুন বিক্রয় তৈরি করা",
    permViewCustomersSuppliers: "গ্রাহক এবং সরবরাহকারী দেখা",
    permCheckStockAlerts: "স্টক অ্যালার্ট চেক করা",
    permViewSaleHistoryStore: "স্টোরের বিক্রয় ইতিহাস দেখা",
    backendRouteProtection: "ব্যাকএন্ড রুট সুরক্ষা",
    backendRouteProtectionDesc: "ইউজার এপিআইগুলো অথেন্টিকেশন এবং অ্যাডমিন অথরাইজেশন দ্বারা সুরক্ষিত। শুধুমাত্র অ্যাডমিন ইউজার তৈরি, আপডেট, স্ট্যাটাস পরিবর্তন এবং ডিলিট করতে পারবেন।",
    salesReport: "বিক্রয় রিপোর্ট",
    analyzeSalesPerformance: "আপনার বিক্রয় কর্মক্ষমতা বিশ্লেষণ করুন",
    totalRevenue: "মোট রাজস্ব",
    totalReceived: "মোট প্রাপ্তি",
    totalOutstanding: "মোট বকেয়া",
    totalInvoices: "মোট ইনভয়েস",
    printReport: "রিপোর্ট প্রিন্ট করুন",
    invoice: "ইনভয়েস",
    paid: "পরিশোধিত",
    noRecordsFoundPeriod: "এই সময়ের জন্য কোনো তথ্য পাওয়া যায়নি",
    walkIn: "সরাসরি গ্রাহক",
    trackStockProcurementSupplierPayments: "স্টক সংগ্রহ এবং সরবরাহকারী পেমেন্ট ট্র্যাক করুন",
    totalPurchases: "মোট ক্রয়",
    paidToSuppliers: "সরবরাহকারীদের পরিশোধিত",
    outstandingDebt: "বকেয়া ঋণ",
    totalOrders: "মোট অর্ডার",
    poNumber: "পিও নম্বর",
    inventoryReport: "ইনভেন্টরি রিপোর্ট",
    stockLevelsAssetValuation: "স্টকের পরিমাণ এবং সম্পদ মূল্যায়ন",
    totalStock: "মোট স্টক",
    stockValue: "স্টক ভ্যালু",
    lowStockItems: "কম স্টক থাকা পণ্য",
    productTypes: "পণ্যের ধরণ",
    filterByStore: "স্টোর অনুযায়ী ফিল্টার",
    currentStock: "বর্তমান স্টক",
    unitPrice: "একক মূল্য",
    totalValue: "মোট মূল্য",
    inStock: "স্টকে আছে",
    businessExpenditureAnalysis: "ব্যবসায়িক ব্যয় বিশ্লেষণ",
    transactionCount: "লেনদেনের সংখ্যা",
    averageExpense: "গড় ব্যয়",
    topCategory: "শীর্ষ ক্যাটাগরি",
    reference: "রেফারেন্স",
    dailySalesReport: "দৈনিক বিক্রয় রিপোর্ট",
    salesSummaryFor: "বিক্রয় সারাংশ -",
    totalDue: "মোট বকেয়া",
    selectDate: "তারিখ নির্বাচন করুন",
    noSalesFoundDate: "এই তারিখে কোনো বিক্রয় পাওয়া যায়নি",
    time: "সময়",
    salesProfitLoss: "বিক্রয় লাভ ও ক্ষতি",
    detailedProfitAnalysisSale: "প্রতিটি বিক্রয়ের বিস্তারিত লাভ বিশ্লেষণ",
    totalCost: "মোট খরচ",
    totalProfit: "মোট লাভ",
    avgMargin: "গড় মার্জিন",
    revenue: "রাজস্ব",
    cost: "খরচ",
    profit: "লাভ",
    margin: "মার্জিন",
    bankPaymentReport: "ব্যাংক পেমেন্ট রিপোর্ট",
    transactionsBankTransfersCards: "ব্যাংক ট্রান্সফার বা কার্ডের মাধ্যমে করা লেনদেনসমূহ",
    accountInfo: "অ্যাকাউন্ট/তথ্য",
    noBankPaymentsFound: "কোনো ব্যাংক পেমেন্ট পাওয়া যায়নি",
    installment: "কিস্তি",
    cashFlowAnalysis: "ক্যাশ ফ্লো বিশ্লেষণ",
    monitorCashInflowOutflow: "নগদ প্রবাহ এবং বহির্গমন পর্যবেক্ষণ করুন",
    totalCashIn: "মোট নগদ প্রবেশ",
    totalCashOut: "মোট নগদ নির্গমন",
    netCashFlow: "নিট নগদ প্রবাহ",
    inflowDetails: "প্রবেশের বিবরণ",
    outflowDetails: "নির্গমনের বিবরণ",
    salePayments: "বিক্রয় পেমেন্টসমূহ",
    installmentPayments: "কিস্তি পেমেন্টসমূহ",
    purchasePayments: "ক্রয় পেমেন্টসমূহ",
    expensePayments: "ব্যয় পেমেন্টসমূহ",
    customerWiseSales: "গ্রাহকভিত্তিক বিক্রয়",
    analyzeSalesPerformanceCustomer: "গ্রাহক অনুযায়ী বিক্রয় কর্মক্ষমতা বিশ্লেষণ করুন",
    productWiseSales: "পণ্যভিত্তিক বিক্রয়",
    analyzeSalesPerformanceProduct: "পণ্য অনুযায়ী বিক্রয় কর্মক্ষমতা বিশ্লেষণ করুন",
    qtySold: "বিক্রীত পরিমাণ",
    refundsReturnsReport: "ফেরত ও রিফান্ড রিপোর্ট",
    trackSalesPurchaseReturns: "সমস্ত বিক্রয় এবং ক্রয় ফেরত ট্র্যাক করুন",
    totalSalesRefunds: "মোট বিক্রয় রিফান্ড",
    totalPurchaseRefunds: "মোট ক্রয় রিফান্ড",
    salesReturns: "বিক্রয় ফেরত",
    purchaseReturns: "ক্রয় ফেরত",
    refund: "রিফান্ড",
    noSalesReturnsFound: "কোনো বিক্রয় ফেরত পাওয়া যায়নি",
    noPurchaseReturnsFound: "কোনো ক্রয় ফেরত পাওয়া যায়নি",
    supplierPerformanceReport: "সরবরাহকারী কর্মক্ষমতা রিপোর্ট",
    overviewSupplierTransactionsDues: "সরবরাহকারী লেনদেন এবং বকেয়ার সংক্ষিপ্ত বিবরণ",
    contactPerson: "যোগাযোগকারী ব্যক্তি",
    purchases: "ক্রয়সমূহ",
    balanceDue: "বকেয়া ব্যালেন্স",
    noSuppliersFound: "কোনো সরবরাহকারী পাওয়া যায়নি",
    supplierProfitabilityAnalysis: "সরবরাহকারী লাভজনকতা বিশ্লেষণ",
    profitMarginsProductsSourcedSuppliers: "নির্দিষ্ট সরবরাহকারীদের থেকে সংগৃহীত পণ্যের লাভের মার্জিন",
    totalNetProfit: "মোট নিট লাভ",
    pleaseSelectSupplierReport: "রিপোর্ট দেখতে দয়া করে একজন সরবরাহকারী নির্বাচন করুন",
    noSalesFoundSupplierProducts: "এই সরবরাহকারীর পণ্যের জন্য কোনো বিক্রয় পাওয়া যায়নি",
    supplierItemAnalysis: "সরবরাহকারী পণ্য বিশ্লেষণ",
    trackProductsSourcedSuppliers: "বিভিন্ন সরবরাহকারীর থেকে সংগৃহীত পণ্য ট্র্যাক করুন",
    itemWisePurchaseReport: "পণ্যভিত্তিক ক্রয় রিপোর্ট",
    analyzeStockPurchasesProduct: "পণ্য অনুযায়ী স্টক ক্রয় বিশ্লেষণ করুন",
    qtyPurchased: "ক্রয়কৃত পরিমাণ",
    dashboardOverview: "ড্যাশবোর্ড ওভারভিউ",
    welcomeBack: "স্বাগতম",
    liveBusinessSummary: "সরাসরি ব্যবসায়িক সারসংক্ষেপ",
    collectedAmount: "সংগৃহীত পরিমাণ",
    customerDue: "গ্রাহকের বকেয়া",
    lowStock: "কম স্টক",
    financialSnapshot: "আর্থিক স্ন্যাপশট",
    revenuePurchaseExpenseProfitComparison: "আয়, ক্রয়, খরচ এবং লাভ তুলনা",
    quickActions: "দ্রুত কাজ",
    frequentlyUsedOperations: "ঘন ঘন ব্যবহৃত কাজগুলো",
    createPosInvoice: "পিওএস ইনভয়েস তৈরি করুন",
    itemsNeedAttention: "আইটেম বিশেষ দৃষ্টি প্রয়োজন",
    receiveNewStock: "নতুন স্টক গ্রহণ করুন",
    viewReportsInvoices: "রিপোর্ট এবং ইনভয়েস দেখুন",
    recentSales: "সাম্প্রতিক বিক্রয়সমূহ",
    loadingRecentSales: "সাম্প্রতিক বিক্রি লোড হচ্ছে...",
    searchProduct: "পণ্য খুঁজুন",
    saleItems: "বিক্রয় আইটেম",
    noItemsAdded: "কোনো আইটেম যোগ করা হয়নি",
    searchCustomerPlaceholder: "কাস্টমার খুঁজুন...",
    discountType: "ডিসকাউন্ট ধরন",
    percentage: "শতকরা (Percentage)",
    fixed: "স্থির (Fixed)",
    discountValue: "ডিসকাউন্টের পরিমাণ",
    vatTax: "ভ্যাট/ট্যাক্স (%)",
    paymentMethod: "পেমেন্ট মাধ্যম",
    cash: "নগদ (Cash)",
    bank: "ব্যাংক (Bank)",
    card: "কার্ড (Card)",
    mobileBanking: "মোবাইল ব্যাংকিং (MFS)",
    paidAmount: "পরিশোধিত টাকা",
    notes: "নোট",
    subtotal: "সাবটোটাল",
    discount: "ডিসকাউন্ট",
    vatAmount: "ভ্যাটের পরিমাণ",
    change: "ফেরত (Change)",
    completeSale: "বিক্রয় সম্পন্ন করুন",
    saving: "সংরক্ষণ হচ্ছে...",
    customerNameRequired: "কাস্টমারের নাম প্রয়োজন",
    failedCreateCustomer: "কাস্টমার তৈরি করতে ব্যর্থ",
    addOneProduct: "দয়া করে অন্তত একটি পণ্য যোগ করুন",
    paidAmountNegative: "পরিশোধিত টাকা নেতিবাচক হতে পারবে না",
    saleFailed: "বিক্রি ব্যর্থ হয়েছে",
    paymentAndDiscount: "পেমেন্ট এবং ডিসকাউন্ট",
    noCategory: "কোনো ক্যাটাগরি নেই",
    billSummary: "বিল সারসংক্ষেপ",
    subTotal: "সাবটোটাল",
    tax: "ট্যাক্স",
    total: "মোট",
    generateInvoice: "ইনভয়েস তৈরি করুন",
    savingSale: "বিক্রয় সংরক্ষণ হচ্ছে...",
    cancel: "বাতিল",
    retail: "খুচরা (Retail)",
    wholesale: "পাইকারি (Wholesale)",
    vip: "ভিআইপি (VIP)",
    totalSales: "মোট বিক্রয়",
    totalPaid: "মোট পরিশোধ",
    totalDue: "মোট বকেয়া",
    invoices: "ইনভয়েসসমূহ",
    searchInvoiceCustomerStore: "ইনভয়েস, কাস্টমার, স্টোর খুঁজুন...",
    allStatus: "সব স্ট্যাটাস",
    selected: "নির্বাচিত",
    exportCsv: "CSV এক্সপোর্ট",
    invoiceNo: "ইনভয়েস নং",
    seller: "বিক্রেতা",
    actions: "অ্যাকশন",
    loadingSales: "বিক্রি তালিকা লোড হচ্ছে...",
    noSaleHistoryFound: "কোনো বিক্রির তথ্য পাওয়া যায়নি",
    showPdf: "PDF দেখুন",
    newPurchase: "নতুন ক্রয়",
    purchaseCreated: "ক্রয় সম্পন্ন হয়েছে",
    poNumber: "PO নম্বর",
    createAnother: "আরেকটি তৈরি করুন",
    selectStore: "স্টোর নির্বাচন করুন",
    selectSupplier: "সাপ্লায়ার নির্বাচন করুন",
    expectedDelivery: "সম্ভাব্য ডেলিভারি",
    receivedDate: "গ্রহণের তারিখ",
    selectProduct: "পণ্য নির্বাচন করুন",
    ordered: "অর্ডার করা হয়েছে",
    received: "পাওয়া গিয়েছে",
    unitCost: "একক খরচ (Unit Cost)",
    itemDiscount: "আইটেম ডিসকাউন্ট",
    finalUnitCost: "চূড়ান্ত একক খরচ",
    payment: "পেমেন্ট",
    taxAmount: "ট্যাক্সের পরিমাণ",
    paymentStatus: "পেমেন্ট স্ট্যাটাস",
    paymentTerms: "পেমেন্ট শর্তাবলী",
    summary: "সারসংক্ষেপ",
    creating: "তৈরি হচ্ছে...",
    createPurchase: "ক্রয় সম্পন্ন করুন",
    storeRequired: "স্টোর প্রয়োজন",
    supplierRequired: "সাপ্লায়ার প্রয়োজন",
    everyItemNeedsProduct: "প্রতিটি আইটেমের জন্য পণ্য প্রয়োজন",
    qtyOrderedPositive: "অর্ডার সংখ্যা ০ এর বেশি হতে হবে",
    qtyReceivedNegative: "প্রাপ্ত সংখ্যা নেতিবাচক হতে পারবে না",
    unitCostRequired: "একক খরচ প্রয়োজন",
    totalPurchase: "মোট ক্রয়",
    records: "রেকর্ডসমূহ",
    searchPoSupplierStore: "PO, সাপ্লায়ার, স্টোর খুঁজুন...",
    loadingPurchases: "ক্রয় তালিকা লোড হচ্ছে...",
    noPurchaseHistoryFound: "কোনো ক্রয়ের তথ্য পাওয়া যায়নি",
    totalReturns: "মোট ফেরত",
    refundAmount: "রিফান্ড পরিমাণ",
    searchReturnPoProduct: "ফেরত, PO, পণ্য খুঁজুন...",
    newReturn: "নতুন ফেরত",
    loadingPurchaseReturns: "ফেরত তালিকা লোড হচ্ছে...",
    noPurchaseReturnFound: "কোনো ফেরতের তথ্য পাওয়া যায়নি",
    returnId: "ফেরত আইডি",
    reason: "কারণ",
    complete: "সম্পন্ন",
    createPurchaseReturn: "ক্রয় ফেরত তৈরি করুন",
    searchPo: "PO খুঁজুন",
    searchPoSupplierPlaceholder: "PO/সাপ্লায়ার খুঁজুন...",
    selectPurchasedProduct: "ক্রয়কৃত পণ্য নির্বাচন করুন",
    refund: "রিফান্ড",
    purchaseReturnDetails: "ক্রয় ফেরতের বিস্তারিত",
    selectPurchaseFirst: "প্রথমে ক্রয় (PO) নির্বাচন করুন",
    selectProductFirst: "প্রথমে পণ্য নির্বাচন করুন",
    quantityRequired: "পরিমাণ প্রয়োজন",
    inventoryRecords: "ইনভেন্টরি রেকর্ড",
    totalQuantity: "মোট পরিমাণ",
    lowOutStock: "কম/শূন্য স্টক",
    stockValue: "স্টকের মূল্য",
    searchInventory: "পণ্য, SKU, স্টোর খুঁজুন...",
    allStores: "সব স্টোর",
    addInventory: "ইনভেন্টরি যোগ করুন",
    noInventoryFound: "কোনো ইনভেন্টরি পাওয়া যায়নি",
    createInventory: "ইনভেন্টরি তৈরি করুন",
    unknownProduct: "অজানা পণ্য",
    unknownStore: "অজানা স্টোর",
    noLocation: "কোনো অবস্থান নেই",
    editInventory: "ইনভেন্টরি সম্পাদনা",
    valuationPrice: "মূল্যায়ন মূল্য",
    locationInStore: "স্টোর অবস্থান",
    fullPreview: "সম্পূর্ণ প্রিভিউ",
    deleteInventoryQuestion: "এই ইনভেন্টরি রেকর্ডটি কি মুছে ফেলতে চান?",
    addingStockFor: "স্টক যোগ করা হচ্ছে: ",
    quantityToAdd: "যোগ করার পরিমাণ",
    enterQuantity: "পরিমাণ লিখুন",
    at: "স্থানে",
    from: "থেকে",
    saving: "সংরক্ষণ হচ্ছে...",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    deleting: "মুছে ফেলা হচ্ছে...",
    totalTransfers: "মোট স্থানান্তর",
    pendingApproval: "অনুমোদনের অপেক্ষায়",
    inTransit: "পথে আছে",
    unitsMoved: "স্থানান্তরিত ইউনিট",
    searchTransferProductSkuStore: "স্থানান্তর, পণ্য, SKU, স্টোর খুঁজুন...",
    newTransfer: "নতুন স্থানান্তর",
    newStockTransfer: "নতুন স্টক স্থানান্তর",
    moveStockFromOneBranchToAnother: "এক শাখা থেকে অন্য শাখায় স্টক স্থানান্তর করুন",
    sourceStore: "উৎস স্টোর",
    destinationStore: "গন্তব্য স্টোর",
    selectSource: "উৎস নির্বাচন করুন",
    selectDestination: "গন্তব্য নির্বাচন করুন",
    writeProductNameOrSku: "পণ্যের নাম বা SKU লিখুন",
    selectSourceStoreFirst: "প্রথমে উৎস স্টোর নির্বাচন করুন",
    noProductsWithStockInThisStore: "এই স্টোরে কোনো পণ্য নেই",
    transferPreview: "স্থানান্তর প্রিভিউ",
    initiateTransfer: "স্থানান্তর শুরু করুন",
    bulkApprove: "একসাথে অনুমোদন",
    availableStock: "বিদ্যমান স্টক",
    sourceDestinationSameError: "উৎস এবং গন্তব্য স্টোর একই হতে পারে না",
    quantityMustBePositive: "পরিমাণ অবশ্যই পজিটিভ হতে হবে",
    insufficientStock: "পর্যাপ্ত স্টক নেই",
    ship: "পাঠান",
    receive: "গ্রহণ করুন",
    done: "সম্পন্ন",
    id: "আইডি",
    source: "উৎস",
    dest: "গন্তব্য",
    createFirstTransfer: "প্রথম স্থানান্তর তৈরি করুন",
    totalReports: "মোট রিপোর্ট",
    pendingReview: "পর্যালোচনার অপেক্ষায়",
    totalLoss: "মোট ক্ষতি",
    searchByProductSkuId: "পণ্য, SKU, আইডি দিয়ে খুঁজুন...",
    reported: "রিপোর্টকৃত",
    reviewed: "পর্যালোচিত",
    discarded: "বাতিলকৃত",
    waterDamage: "পানির ক্ষতি",
    physicalDamage: "শারীরিক ক্ষতি",
    defectiveProduct: "ত্রুটিপূর্ণ পণ্য",
    transitDamage: "পরিবহনের ক্ষতি",
    fireSmoke: "আগুন/ধোঁয়া",
    theftMissing: "চুরি/নিখোঁজ",
    pestInfestation: "পোকামাকড়ের উপদ্রব",
    reportDamagedStock: "ক্ষতিগ্রস্ত স্টক রিপোর্ট",
    documentDamageIncident: "ক্ষতি বা লোকসানের ঘটনা নথিভুক্ত করুন",
    quantityDamaged: "ক্ষতির পরিমাণ",
    lossAmount: "ক্ষতির অংক",
    estimatedCostLoss: "আনুমানিক খরচ/ক্ষতি",
    damageType: "ক্ষতির ধরন",
    damageDescription: "ক্ষতির বর্ণনা",
    describeDamageInDetail: "ক্ষতির বিস্তারিত বর্ণনা দিন",
    initialActionTaken: "প্রাথমিক পদক্ষেপ",
    anyImmediateActionTaken: "তাৎক্ষণিক কোনো পদক্ষেপ নেওয়া হয়েছে?",
    reporting: "রিপোর্ট হচ্ছে...",
    submitDamageReport: "ক্ষতি রিপোর্ট জমা দিন",
    damageReportDetails: "ক্ষতি রিপোর্টের বিস্তারিত",
    dateReported: "রিপোর্টের তারিখ",
    reportedBy: "রিপোর্ট করেছেন",
    actionTakenNotes: "গৃহীত পদক্ষেপের নোট",
    review: "পর্যালোচনা",
    resolve: "সমাধান করুন",
    discard: "বাতিল করুন",
    unit: "ইউনিট",
    units: "ইউনিট",
    stockAlert: "স্টক অ্যালার্ট",
    stockAlertSubtitle: "এপিআই থেকে কম স্টক, স্টক নেই এবং অতিরিক্ত স্টক পণ্যের তথ্য",
    refresh: "রিফ্রেশ",
    lowStock: "কম স্টক",
    outOfStock: "স্টক নেই",
    overstock: "অতিরিক্ত স্টক",
    showing: "দেখানো হচ্ছে",
    searchProductSkuStore: "পণ্য, SKU, স্টোর খুঁজুন...",
    lowOutStockAlert: "কম / স্টক নেই",
    loadingStockAlerts: "স্টক অ্যালার্ট লোড হচ্ছে...",
    noOverstockAlerts: "অতিরিক্ত স্টকের কোনো তথ্য নেই",
    noLowStockAlerts: "কম স্টকের কোনো তথ্য নেই",
    extra: "অতিরিক্ত",
  },
};

export { translations };

export const useLanguageStore = create((set, get) => ({
  lang: savedLang,

  setLang: (lang) => {
    localStorage.setItem("lang", lang);
    set({ lang });
  },

  toggleLang: () => {
    const next = get().lang === "en" ? "bn" : "en";
    localStorage.setItem("lang", next);
    set({ lang: next });
  },

  t: (key) => translations[get().lang]?.[key] || translations.en[key] || key,
}));
