import { create } from "zustand";

const savedLang = localStorage.getItem("lang") || "en";

export const translations = {
  en: {
    dashboard: "Dashboard",
    newSale: "New Sale",
    purchase: "Purchase",
    notifications: "Notifications",
    live: "Live",
    viewStockAlerts: "View stock alerts",
    totalSales: "Total Sales",
    purchases: "Purchases",
    dueAmount: "Due Amount",
    lowStockItems: "Low Stock Items",
    sales: "sales",
    cost: "Cost",
    pending: "Pending",
    alert: "Alert",
    myProfile: "My Profile",
    reports: "Reports",
    settings: "Settings",
    signOut: "Sign Out",
    noStore: "No Store",
    noRole: "No Role",
    language: "Language",
    english: "English",
    bangla: "বাংলা",
    // side bar
    saleHistory: "Sale History",
    saleReturns: "Sale Returns",
    installments: "Installments",
    newPurchase: "New Purchase",
    purchaseHistory: "Purchase History",
    purchaseReturns: "Purchase Returns",
    inventory: "Inventory",
    stockOverview: "Stock Overview",
    lowStockAlert: "Low Stock Alert",
    stockTransfer: "Stock Transfer",
    damageStock: "Damage Stock",
    products: "Products",
    allProducts: "All Products",
    addProduct: "Add Product",
    categories: "Categories",
    customers: "Customers",
    allCustomers: "All Customers",
    addCustomer: "Add Customer",
    suppliers: "Suppliers",
    allSuppliers: "All Suppliers",
    addSupplier: "Add Supplier",
    expenses: "Expenses",
    allExpenses: "All Expenses",
    addExpense: "Add Expense",
    yearlyTracking: "Yearly Tracking",
    salesReport: "Sales Report",
    purchaseReport: "Purchase Report",
    inventoryReport: "Inventory Report",
    expenseReport: "Expense Report",
    profitLoss: "Profit & Loss",
    reportsOverview: "Reports Overview",
    dailySales: "Daily Sales",
    productSales: "Product Sales",
    customerSales: "Customer Sales",
    itemPurchase: "Item Purchase",
    supplierReport: "Supplier Report",
    cashFlow: "Cash Flow",
    bankPayments: "Bank Payments",
    refunds: "Refunds & Returns",
    users: "Users",
    allUsers: "All Users",
    addUser: "Add User",
    roles: "Roles",
    stores: "Stores",
    allStores: "All Stores",
    addStore: "Add Store",
    posSystem: "POS SYSTEM",
  },

  bn: {
    dashboard: "ড্যাশবোর্ড",
    newSale: "নতুন বিক্রি",
    purchase: "ক্রয়",
    notifications: "নোটিফিকেশন",
    live: "লাইভ",
    viewStockAlerts: "স্টক অ্যালার্ট দেখুন",
    totalSales: "মোট বিক্রি",
    purchases: "মোট ক্রয়",
    dueAmount: "বাকি টাকা",
    lowStockItems: "লো স্টক আইটেম",
    sales: "বিক্রি",
    cost: "খরচ",
    pending: "বাকি",
    alert: "অ্যালার্ট",
    myProfile: "আমার প্রোফাইল",
    reports: "রিপোর্ট",
    settings: "সেটিংস",
    signOut: "সাইন আউট",
    noStore: "স্টোর নেই",
    noRole: "রোল নেই",
    language: "ভাষা",
    english: "English",
    bangla: "বাংলা",
    // Side Bar
    saleHistory: "বিক্রির হিস্টোরি",
    saleReturns: "বিক্রি রিটার্ন",
    installments: "কিস্তি",
    newPurchase: "নতুন ক্রয়",
    purchaseHistory: "ক্রয় হিস্টোরি",
    purchaseReturns: "ক্রয় রিটার্ন",
    inventory: "ইনভেন্টরি",
    stockOverview: "স্টক ওভারভিউ",
    lowStockAlert: "লো স্টক অ্যালার্ট",
    stockTransfer: "স্টক ট্রান্সফার",
    damageStock: "ড্যামেজ স্টক",
    products: "পণ্য",
    allProducts: "সব পণ্য",
    addProduct: "পণ্য যোগ করুন",
    categories: "ক্যাটাগরি",
    customers: "কাস্টমার",
    allCustomers: "সব কাস্টমার",
    addCustomer: "কাস্টমার যোগ করুন",
    suppliers: "সাপ্লায়ার",
    allSuppliers: "সব সাপ্লায়ার",
    addSupplier: "সাপ্লায়ার যোগ করুন",
    expenses: "খরচ",
    allExpenses: "সব খরচ",
    addExpense: "খরচ যোগ করুন",
    yearlyTracking: "বার্ষিক ট্র্যাকিং",
    salesReport: "বিক্রি রিপোর্ট",
    purchaseReport: "ক্রয় রিপোর্ট",
    inventoryReport: "ইনভেন্টরি রিপোর্ট",
    expenseReport: "খরচ রিপোর্ট",
    profitLoss: "লাভ-ক্ষতি",
    reportsOverview: "রিপোর্ট ওভারভিউ",
    dailySales: "দৈনিক বিক্রি",
    productSales: "পণ্য ভিত্তিক বিক্রি",
    customerSales: "কাস্টমার ভিত্তিক বিক্রি",
    itemPurchase: "আইটেম ভিত্তিক ক্রয়",
    supplierReport: "সাপ্লায়ার রিপোর্ট",
    cashFlow: "ক্যাশ ফ্লো",
    bankPayments: "ব্যাংক পেমেন্ট",
    refunds: "রিফান্ড ও রিটার্ন",
    users: "ইউজার",
    allUsers: "সব ইউজার",
    addUser: "ইউজার যোগ করুন",
    roles: "রোল",
    stores: "স্টোর",
    allStores: "সব স্টোর",
    addStore: "স্টোর যোগ করুন",
    posSystem: "পিওএস সিস্টেম",
  },
};

export const useLanguageStore = create((set, get) => ({
  lang: savedLang,

  setLang: (lang) => {
    localStorage.setItem("lang", lang);
    set({ lang });
  },

  toggleLang: () => {
    const next = get().lang === "en" ? "bn" : "en";
    localStorage.setItem("lang", next);
    set({ lang: next });
  },

  t: (key) => translations[get().lang]?.[key] || translations.en[key] || key,
}));
